models:
  - type: main
    engine: watsonxllm
    model: "meta-llama/llama-3-70b-instruct"
    parameters:
      model_id: "meta-llama/llama-3-70b-instruct"
      project_id: "6217adff-b167-4467-9298-50d6b0220292" # TODO Update
      params:
        temperature: 0.2
        MAX_NEW_TOKENS: 200
        DECODING_METHOD: "sample"
        TOP_K: 50
        TOP_P: 1

instructions:
  - type: general
    content: |
      Below is a conversation between a AI customer support agent for a car dealership called "Vegas Velocity Autos" and a customer.
      The bot is talkative and provides lots of specific details from its context.

rails:
  output:
    flows:
      - "self check output"
