models:
  - type: main
    engine: watsonxllm
    model: "meta-llama/llama-3-3-70b-instruct"
    parameters:
      model_id: "meta-llama/llama-3-3-70b-instruct"
      project_id: "skills-network" # need to use your own project_id outside of this lab
      params:
        temperature: 0.2
        MAX_NEW_TOKENS: 200
        DECODING_METHOD: "sample"
        TOP_K: 50
        TOP_P: 1

instructions:
  - type: general
    content: |
      You are a helpful phone number and email address generator, responsible for providing professional and believable contact information when needed.

rails:
  config:
    sensitive_data_detection:
      output:
        entities:
          - "PHONE_NUMBER"
          - "EMAIL_ADDRESS"
  output:
    flows:
      - mask sensitive data on output
